import { ArrowDownRight, ArrowUpRight, CircleUserRound, Menu, Plus, X } from "lucide-react";
import { useState, type ReactNode } from "react";

const people = [
  { name: "江明倢 Sho", role: "商業接洽　概念設計", image: "https://images.unsplash.com/photo-1761554169693-08fd975a94f8?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=1000", position: "md:col-span-4 md:col-start-2 md:mt-28" },
  { name: "陳子璇 Eleanor", role: "專案管理　邏輯分析", image: "https://images.unsplash.com/photo-1771072427776-9142b2d39a26?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=1000", position: "md:col-span-3 md:col-start-7" },
  { name: "蔡孟軒 Alvin", role: "工程實作　產品打樣", image: "https://images.unsplash.com/photo-1761554169700-131bc3f188c3?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=1000", position: "md:col-span-4 md:col-start-10 md:mt-44" },
];

const projects = [
  { id: "01", title: "《小封神藏寶圖》", type: "遊戲道具 / 視覺系統", date: "2026年 7月14日", visual: "map", position: "md:col-span-7" },
  { id: "02", title: "《劍道賽計分板》", type: "產品設計 / 賽事系統", date: "2026年 4月21日", visual: "score", position: "md:col-span-5 md:mt-24" },
  { id: "03", title: "《PVD鍍膜機外觀設計》", type: "工業設計 / 設備外觀", date: "2025年 12月08日", visual: "machine", position: "md:col-span-5 md:mt-4" },
  { id: "04", title: "《PVD鍍膜機VR操作模擬系統》", type: "UI/UX / VR INTERFACE", date: "2025年 9月17日", visual: "vr", position: "md:col-span-7 md:mt-28" },
];

function Label({ children }: { children: ReactNode }) {
  return <p className="font-mono text-[10px] font-medium tracking-[0.13em] text-muted-foreground sm:text-xs">{children}</p>;
}

function ProjectVisual({ type }: { type: string }) {
  if (type === "map") return <div className="relative flex size-full items-center justify-center overflow-hidden bg-[#d77a5c]"><div className="absolute inset-5 border border-[#20201d]/60"/><div className="relative h-[64%] w-[54%] rotate-[-7deg] border-2 border-[#20201d] bg-[#f0d49c] p-3 shadow-[11px_11px_0_#20201d]"><span className="font-[Noto_Serif_TC] text-3xl font-black">小封神</span><div className="mt-4 h-10 border-y border-[#20201d] border-dashed"/><div className="mt-3 flex justify-between font-mono text-[9px]"><span>北 24°</span><span>寶圖 01</span></div></div></div>;
  if (type === "score") return <div className="grid size-full place-items-center bg-[#272a2f]"><div className="grid w-[78%] grid-cols-2 border-4 border-[#e7e2d6] p-1 text-center font-[Space_Grotesk] text-5xl font-bold leading-none text-[#e7e2d6] shadow-[10px_10px_0_#cf664b] sm:text-7xl"><span className="border-r border-[#e7e2d6] p-4">02</span><span className="p-4">01</span><span className="col-span-2 border-t border-[#e7e2d6] p-2 font-mono text-[10px] tracking-[.2em]">KENDO / MATCH 12</span></div></div>;
  if (type === "machine") return <div className="relative grid size-full place-items-center overflow-hidden bg-[#aeb2ac]"><div className="absolute left-0 top-[24%] h-px w-full bg-[#20201d]/30"/><div className="relative h-[58%] w-[68%] border-[10px] border-[#20201d] bg-[#e1e0d8] shadow-[14px_14px_0_#cf664b]"><div className="absolute left-[20%] top-[18%] size-[35%] rounded-full border-[9px] border-[#20201d] bg-[#8a9695]"/><div className="absolute bottom-0 left-[12%] h-5 w-[23%] bg-[#20201d]"/><div className="absolute bottom-0 right-[12%] h-5 w-[23%] bg-[#20201d]"/></div></div>;
  return <div className="relative grid size-full place-items-center overflow-hidden bg-[#6e7785]"><div className="absolute size-[125%] rotate-45 border border-[#e9e5d9]/40"/><div className="relative h-[55%] w-[72%] rounded-[50%] border-[10px] border-[#20201d] bg-[#e9e5d9] shadow-[12px_12px_0_#cf664b]"><div className="absolute left-[18%] top-[32%] size-7 rounded-full border-2 border-[#20201d]"/><div className="absolute right-[18%] top-[32%] size-7 rounded-full border-2 border-[#20201d]"/><span className="absolute bottom-[-24px] left-1/2 -translate-x-1/2 whitespace-nowrap font-mono text-[9px] text-[#e9e5d9]">IMMERSIVE CONTROL</span></div></div>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeDot, setActiveDot] = useState(0);

  return <main className="min-h-screen bg-background font-[Noto_Sans_TC] text-foreground"><div className="mx-auto max-w-[1600px] overflow-hidden border-x border-border bg-background">
    <div className="flex h-9 items-center border-b border-border px-3 font-mono text-[9px] tracking-[.08em] text-muted-foreground sm:px-4"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-[#c75d4a]"/><i className="size-2 rounded-full bg-[#cba85d]"/><i className="size-2 rounded-full bg-[#82937f]"/></div><span className="mx-auto border border-border bg-card px-12 py-0.5">dm-df.studio / 2026</span><span className="hidden sm:block">TW / 22.63°N</span></div>
    <header className="relative flex h-16 items-center justify-between border-b border-border px-4 sm:px-6 md:px-8"><a href="#top" className="font-mono text-[11px] tracking-[.12em]">DMDF®</a><nav className="hidden gap-7 font-mono text-[10px] tracking-[.12em] md:flex"><a href="#people">成員 PEOPLE</a><a href="#projects">作品 WORK</a><a href="#contact">聯絡 CONTACT</a></nav><button onClick={() => setMenuOpen(!menuOpen)} className="grid size-8 place-items-center border border-border md:hidden" aria-label="開啟選單">{menuOpen ? <X size={17}/> : <Menu size={17}/>}</button>{menuOpen && <nav className="absolute left-0 top-full z-20 flex w-full flex-col border-b border-border bg-background px-4 py-3 font-mono text-xs tracking-[.1em] shadow-[0_12px_0_rgba(32,32,29,.12)] md:hidden">{[["#people","成員 PEOPLE"],["#projects","作品 WORK"],["#contact","聯絡 CONTACT"]].map(([href, text]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="border-t border-border py-3">{text}</a>)}</nav>}</header>
    <section id="top" className="border-b border-border px-4 pb-10 pt-6 sm:px-6 md:px-8 md:pb-16"><div className="mb-12 flex justify-between"><Label>01 — DMD F, DESIGN COLLECTIVE</Label><Label>KAOHSIUNG / TAIWAN</Label></div><h1 className="font-[Space_Grotesk] text-[clamp(4.1rem,15vw,14rem)] font-bold leading-[.76] tracking-[-.105em]">大<span className="font-[Noto_Serif_TC] text-[#cf664b]">明</span>大放<span className="ml-[.12em] text-[.29em] tracking-[-.065em]">設計工作室</span></h1><div className="mt-5 flex items-end justify-between border-t border-border pt-3"><p className="font-[Space_Grotesk] text-xl font-medium tracking-[-.055em] sm:text-3xl">Da ming Da Fun</p><ArrowDownRight size={28} strokeWidth={1.25}/></div><div className="mt-12 grid gap-6 sm:grid-cols-12"><p className="font-mono text-[11px] leading-relaxed text-muted-foreground sm:col-span-4">為想法建立可被看見、使用與記住的形式。</p><p className="font-mono text-[11px] leading-relaxed text-muted-foreground sm:col-span-5 sm:col-start-8">產品設計、平面設計、品牌建立、互動設計</p></div></section>
    <section id="people" className="border-b border-border py-12 md:py-20"><div className="mb-9 flex items-end justify-between px-4 sm:px-6 md:px-8"><div><Label>02 — THE STUDIO</Label><h2 className="mt-1 text-xl font-bold tracking-[-.04em]">各自專精，一起完成</h2></div><span className="font-mono text-[10px]">01—03</span></div><div className="grid grid-cols-1 gap-12 px-4 sm:px-6 md:grid-cols-13 md:gap-x-4 md:gap-y-0 md:px-8">{people.map((person, i) => <article className={person.position} key={person.name}><div className="relative aspect-[3/4] overflow-hidden bg-muted"><img src={person.image} alt={`${person.name} ${person.role}`} className="size-full object-cover grayscale-[22%] sepia-[11%] contrast-[.92] transition duration-700 hover:scale-[1.03]"/><span className="absolute bottom-2 left-2 bg-background px-1.5 py-1 font-mono text-[10px]">0{i + 1}</span></div><div className="mt-2 flex justify-between border-t border-foreground pt-2"><div><p className="font-bold tracking-[-.035em]">{person.name}</p><p className="mt-1 font-mono text-[10px] tracking-[.06em] text-muted-foreground">{person.role}</p></div><ArrowUpRight size={16} strokeWidth={1.3}/></div></article>)}</div><div className="mt-14 flex justify-center gap-2 md:mt-20">{[0,1,2].map(dot => <button onClick={() => setActiveDot(dot)} key={dot} aria-label={`第${dot+1}位成員`} className={`size-2 rounded-full border border-foreground ${activeDot === dot ? "bg-foreground" : "bg-transparent"}`}/>)}</div></section>
    <section id="projects" className="py-12 md:py-20"><div className="flex items-end justify-between px-4 sm:px-6 md:px-8"><div><Label>03 — SELECTED PROJECTS</Label><h2 className="mt-1 text-xl font-bold tracking-[-.04em]">商業作品</h2></div><span className="font-mono text-[10px]">2025—26</span></div><div className="mt-8 grid grid-cols-1 gap-x-4 gap-y-10 px-4 sm:px-6 md:grid-cols-12 md:px-8">{projects.map(project => <article key={project.id} className={`group ${project.position}`}><div className="aspect-[4/3] overflow-hidden"><ProjectVisual type={project.visual}/></div><div className="mt-2 border-t border-foreground pt-2"><div className="flex justify-between"><Label>{project.type}</Label><span className="font-mono text-[10px]">{project.id}</span></div><h3 className="mt-7 font-[Space_Grotesk] text-2xl font-bold leading-[.98] tracking-[-.055em] sm:text-3xl">{project.title}</h3><div className="mt-7 flex items-end justify-between border-t border-border pt-2"><span className="font-mono text-[10px] text-muted-foreground">{project.date}</span><ArrowUpRight size={18}/></div></div></article>)}</div></section>
    <footer id="contact" className="border-t border-border"><div className="grid border-b border-border md:grid-cols-[auto_1fr]"><div className="flex min-h-40 w-full items-end justify-center border-b border-border pb-5 md:w-20 md:border-b-0 md:border-r"><CircleUserRound size={25} strokeWidth={1.3}/></div><div className="p-5 sm:p-7 md:p-9"><Label>CONTACT / 委託合作</Label><a className="mt-5 block w-fit font-[Space_Grotesk] text-[clamp(1.8rem,5vw,4.6rem)] font-bold leading-none tracking-[-.075em] underline decoration-[#cf664b] decoration-[.12em] underline-offset-[.18em] transition-colors hover:text-[#cf664b]" href="mailto:0800guava@gmail.com">0800guava@gmail.com</a></div></div><div className="border-b border-border px-5 py-7 sm:px-7 md:px-9 md:py-10"><Label>LONG-TERM COLLABORATORS / 長期合作對象</Label><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><span className="font-[Noto_Serif_TC] text-3xl font-bold tracking-[-.04em] sm:text-5xl">Sultani Coffee</span><span className="font-[Space_Grotesk] text-3xl font-bold tracking-[-.075em] sm:text-5xl">Meow Party Café</span><span className="grid size-8 place-items-center rounded-full bg-foreground text-background"><Plus size={17}/></span></div></div><div className="flex items-center justify-between px-5 py-4 sm:px-7 md:px-9"><span className="font-[Space_Grotesk] text-xl font-bold tracking-[-.075em]">大明大放設計工作室</span><span className="font-mono text-[10px] text-muted-foreground">© 2026 / TAIWAN</span></div></footer>
  </div></main>;
}
